site_name: mivp-agent
site_url: http://mivp-agent.github.io

plugins:
    - mkdocstrings:
        watch:
            - mivp_agent
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Python API:
        - MissionManager: python/mission_manager.md
        - MissionMessage: python/mission_message.md 
    - MOOS-IvP Reference:
        - BHV_Agent: moos_ivp/bhv_agent.md
        - pEpisodeManager: moos_ivp/pEpisodeManager

theme:
    name: "material"
    palette:
        primary: green
    icon:
        repo: fontawesome/brands/github

# For styling of components like buttons
markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

# Turn of "Made with MkDocs"
extra:
    analytics:
        provider: google
        property: G-FD1VZZ2BGB
    generator: false

# Base location for editing of docs
edit_uri: https://github.com/mivp-agent/mivp-agent.github.io/tree/master/docs

# Repo displace in material theme
repo_url: https://github.com/CarterFendley/moos-ivp-agent
repo_name: CarterFendley/moos-ivp-agent

copyright: Copyright &copy; 2021 Carter Fendley

